sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

matrix:
  - php: 5.4
  - php: 5.5
    env:
     - EXECUTE_CS_CHECK=true
  - php: 5.6
  - php: 7
  - php: hhvm

before_script:
 - composer install --prefer-dist

script:
 - composer test
 - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

matrix:
  allow_failures:
    - php: hhvm
